spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL_ADDRESS}
    password: ${SENDER_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

