spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL_ADDRESS:default-user}
    password: ${SENDER_MAIL_PASSWORD:default-password}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

