spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL_ADDRESS}
    password: ${SENDER_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    email:
      name: email_queue
  exchange:
    email:
      name: email_exchange
  binding:
    email:
      name: email_routing_key
